services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8803:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - API_KEY=${API_KEY}
      - MODEL=${MODEL}
      - API_URL=${API_URL}
    restart: unless-stopped
    volumes:
      - ./public:/app/public
      - ./.next/cache:/app/.next/cache
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    env_file:
      - .env
